appSettings:
  httpClientRequestTimeOutSeconds: 2.0
  baseFileLocationFolder: "C:\\Users\\AmerMaqsood\\Downloads"
  fhirServerUrl: "https://terminology.esmdval.cms.gov:8099"
  endPointBaseUrl: "https://val.cpiapigateway.cms.gov"

  authenticationAPI:
    clientId: "ENTER YOUR CLIENT ID"
    clientSecret: "ENTER YOUR CLIENT SECRET"
    scope: "hih/esmdfhir"
    endpointURL: "${endPointBaseUrl}/api/esmdf/auth/generate"
    contentType: "application/json"
    httpClientRequestTimeOutSeconds: 2.0

  presignedURLAPI:
    endpointURL: "${endPointBaseUrl}/api/esmdf/v1/fhir/DocumentReference/$generate-presigned-url"
    contentType: "application/fhir+json"
    accept: "application/fhir+json"
    httpClientRequestTimeOutSeconds: 2.0
    request:
      resourceType: "Parameters"
      id: ""
      parameter:
        - name: "organizationid"
          valueString: "urn:oid:123.456.657.126"
        - name: "fileinfo"
          part:
            - name: "filename"
              valueString: "presigned_url_xml_file.xml"
            - name: "content-md5"
              valueString: ""
            - name: "filesize"
              valueString: ""
            - name: "mimetype"
              valueString: "application/xml"

  uploadClinicalDocumentAPI:
    contentType: "application/xml"
    httpClientRequestTimeOutSeconds: 4.0
    fileName: "presigned_url_xml_file.xml"
    contentMD5: ""

  bundleSubmissionAPI:
    endpointURL: "${endPointBaseUrl}/api/esmdf/v1/fhir"
    contentType: application/fhir+json
    accept: application/fhir+json
    httpClientRequestTimeOutSeconds: 4.0
    request:
      resourceType: Bundle
      id: ""
      meta:
        profile:
          - "${fhirServerUrl}/fhir/StructureDefinition/Esmd-BundleSubmission"
        security:
          - system: http://terminology.hl7.org/CodeSystem/v3-Confidentiality
            code: V
            display: very restricted
      type: transaction
      timestamp: ""
      entry:
        - fullUrl: ""
          resource:
            resourceType: List
            id: ""
            meta:
              profile:
                - "${fhirServerUrl}/fhir/StructureDefinition/Esmd-ListSubmissionSet"
              security:
                - system: http://terminology.hl7.org/CodeSystem/v3-Confidentiality
                  code: V
                  display: very restricted
            extension:
              - url: "${fhirServerUrl}/fhir/StructureDefinition/Esmd-Ext-LinesOfBusinessId"
                valueCode: "11.1"
              - url: "${fhirServerUrl}/fhir/StructureDefinition/Esmd-Ext-OrganizationId"
                valueString: "urn:oid:123.456.657.126"
              - url: "${fhirServerUrl}/fhir/StructureDefinition/Esmd-Ext-IntendedRecipient"
                valueCode: "urn:oid:2.16.840.1.113883.13.34.110.1.999.1"
              - url: "${fhirServerUrl}/fhir/StructureDefinition/Esmd-Ext-UniqueId"
                valueString: ""
              - url: "${fhirServerUrl}/fhir/StructureDefinition/Esmd-Ext-NPI"
                valueString: "1234567893"
              - url: "${fhirServerUrl}/fhir/StructureDefinition/Esmd-Ext-ResponseTypeCategory"
                valueString: "ResponseTypeCategory Value"
            status: current
            mode: working
            title: Submission Set Title
            date: ""
            entry:
              - item:
                  reference: ""
          request:
            method: POST
            url: List

        - fullUrl: ""
          resource:
            resourceType: DocumentReference
            id: ""
            meta:
              profile:
                - "${fhirServerUrl}/fhir/StructureDefinition/Esmd-DocumentReference"
              security:
                - system: http://terminology.hl7.org/CodeSystem/v3-Confidentiality
                  code: V
                  display: very restricted
            identifier:
              - system: "${fhirServerUrl}/fhir/StructureDefinition/Esmd-Idn-UniqueId"
                value: ""
            status: current
            date: ""
            category:
              - coding:
                  - system: http://loinc.org
                    code: 47039-3
                    display: Hospital Admission history and physical note
            securityLabel:
              - coding:
                  - system: http://terminology.hl7.org/CodeSystem/v3-Confidentiality
                    code: V
                    display: very restricted
            content:
              - attachment:
                  id: ""
                  contentType: ""
                  url: ""
                  size: 1
                  hash: ""
                  title: ""
                  creation: ""
                format:
                  system: urn:oid:1.3.6.1.4.1.19376.1.2.3
                  code: urn:ihe:iti:xds-sd:pdf:2008
            context:
              facilityType:
                coding:
                  - system: "${fhirServerUrl}/fhir/CodeSystem/Esmd-CS-FacilityTypeCodes"
                    code: hih
                    display: Health Information Handler (HIH)
                  - system: "${fhirServerUrl}/fhir/CodeSystem/Esmd-CS-FacilityTypeCodes"
                    code: hcp
                    display: Health Care Provider
                  - system: "${fhirServerUrl}/fhir/CodeSystem/Esmd-CS-FacilityTypeCodes"
                    code: cms-rc
                    display: CMS Review Contractor
          request:
            method: POST
            url: DocumentReference
  
  notificationRetrievalAPI:
    endpointURL: "${endPointBaseUrl}/api/esmdf/v1/fhir/List"
    accept: "application/fhir+json"
    httpClientRequestTimeOutSeconds: 4.0
    requestParameters:
      - name: "transaction-status-type"
        value: "ready-to-download"
        inject: false
      - name: "requesttype"
        value: "ADMIN_ERROR"
        inject: false
      - name: "uniqueid"
        value: ""
        inject: false

  documentRetrievalAPI:
    endpointURL: "${endPointBaseUrl}/api/esmdf/v1/fhir/DocumentReference"
    accept: "application/fhir+json"
    httpClientRequestTimeOutSeconds: 4.0
    requestParameters:
      - name: "transaction-status-type"
        value: "ready-to-download"
        inject: false
      - name: "uniqueid"
        value: ""
        inject: false

  deliveryConfirmationAPI:
    endpointURL: "${endPointBaseUrl}/api/esmdf/v1/fhir/List"
    accept: "application/fhir+json"
    contentType: "application/fhir+json"
    httpClientRequestTimeOutSeconds: 4.0
    request:
      resourceType: "List"
      id: "0187157c-da3f-4a74-b687-423bab362754"
      meta:
        profile:
          - "${fhirServerUrl}/fhir/StructureDefinition/Esmd-ListDeliveryConfirmation"
      contained:
        - resourceType: "OperationOutcome"
          id: "UPW0081445906EC-OperationOutcome"
          meta:
            profile:
              - "${fhirServerUrl}/fhir/StructureDefinition/Esmd-OperationOutcome"
            security:
              - system: "http://terminology.hl7.org/CodeSystem/v3-Confidentiality"
                code: "V"
                display: "Very-Restricted"
          issue:
            - severity: "information"
              code: "informational"
              diagnostics: "Transaction notification retrieved successfully"
      extension:
        - url: "${fhirServerUrl}/fhir/StructureDefinition/Esmd-Ext-TransactionId"
          valueString: "UPW0081445906EC"
        - url: "${fhirServerUrl}/fhir/StructureDefinition/Esmd-Ext-OrganizationId"
          valueString: "urn:oid:123.456.657.127"
        - url: "${fhirServerUrl}/fhir/StructureDefinition/Esmd-Ext-DeliveryDateTime"
          valueDateTime: "2025-09-08T15:11:41.947-04:00"
        - url: "${fhirServerUrl}/fhir/StructureDefinition/Esmd-Ext-NPI"
          valueString: "1568425007"
      status: "current"
      mode: "working"
      title: "Submission Set Title"
      date: "2025-09-08T15:11:41.947-04:00"
      entry:
        - item:
            reference: "#UPW0081445906EC-OperationOutcome"

  practitionerAPI:
    endpointURL: "${endPointBaseUrl}/api/esmdf/v1/fhir/Practitioner/{id}"
    accept: "application/fhir+json"
    contentType: "application/fhir+json"
    httpClientRequestTimeOutSeconds: 4.0
    request:
      resourceType: "Practitioner"
      id: "PRACT1234"
      meta:
        profile:
          - "${fhirServerUrl}/fhir/StructureDefinition/Esmd-Practitioner"
        security:
          - system: "http://terminology.hl7.org/CodeSystem/v3-Confidentiality"
            code: "V"
            display: "very restricted"
      name:
        - family: "Gaven"
          given: [ "Radems" ]
          prefix: [ "Dr" ]
          suffix: [ "Ph.D" ]
      telecom:
        - system: "phone"
          value: "551-333-6141"
          use: "work"
      address:
        - use: "work"
          line: [ "1003 MILLERS DR" ]
          city: "ELLICOTT CITY"
          state: "MD"
          postalCode: "21043"
      gender: "female"
      active: true
      extension:
        - url: "${fhirServerUrl}/fhir/StructureDefinition/Esmd-Ext-NPI"
          valueString: "1700962487"
        - url: "${fhirServerUrl}/fhir/StructureDefinition/Esmd-Ext-ProviderTaxId"
          valueString: "101-56-55"
        - url: "${fhirServerUrl}/fhir/StructureDefinition/Esmd-Ext-ActionRequestedCode"
          valueCode: "A"
        - url: "${fhirServerUrl}/fhir/StructureDefinition/Esmd-Ext-ServiceCode"
          valueCode: "EEP"
        - url: "${fhirServerUrl}/fhir/StructureDefinition/Esmd-Ext-ServiceStartDate"
          valueDate: "2025-10-01"
        - url: "${fhirServerUrl}/fhir/StructureDefinition/Esmd-Ext-ServiceEndDate"
          valueDate: "2026-12-30"

  binaryAPI:
    endpointURL: "${endPointBaseUrl}/api/esmdf/v1/fhir/Binary/{id}"
    accept: "application/fhir+json"
    fileNameId: "TXE0007232564EC_20250305105429_2"
    httpClientRequestTimeOutSeconds: 4.0

  bundlePractitionerAPI:
    endpointURL: "${endPointBaseUrl}/api/esmdf/v1/fhir"
    contentType: "application/fhir+json"
    accept: "application/fhir+json"
    httpClientRequestTimeOutSeconds: 4.0
    request:
      resourceType: "Bundle"
      id: "${PractitionerIdValue}"
      meta:
        profile:
          - "${fhirServerUrl}/fhir/StructureDefinition/Esmd-BundleServiceRegistration"
        security:
          - system: "http://terminology.hl7.org/CodeSystem/v3-Confidentiality"
            code: "V"
            display: "very restricted"
      type: "batch"
      timestamp: "2025-04-13T12:00:00Z"
      entry:
        - fullUrl: "urn:uuid:1"
          resource:
            resourceType: "Practitioner"
            id: "P${PractitionerIdValue}"
            meta:
              profile:
                - "${fhirServerUrl}/fhir/StructureDefinition/Esmd-Practitioner"
              security:
                - system: "http://terminology.hl7.org/CodeSystem/v3-Confidentiality"
                  code: "V"
                  display: "very restricted"
            telecom:
              - system: "phone"
                value: "555-123-4567"
                use: "work"
            name:
              - family: "Bone1"
                given:
                  - "Ronald1"
                prefix:
                  - "Dr"
            address:
              - use: "work"
                line:
                  - "1003 HEALTHCARE DR"
                city: "AMHERST"
                state: "MA"
                postalCode: "01002"
            gender: "male"
            active: true
            extension:
              - url: "${fhirServerUrl}/fhir/StructureDefinition/Esmd-Ext-NPI"
                valueString: "1467487009"
              - url: "${fhirServerUrl}/fhir/StructureDefinition/Esmd-Ext-ProviderTaxId"
                valueString: "HIH1234"
              - url: "${fhirServerUrl}/fhir/StructureDefinition/Esmd-Ext-ActionRequestedCode"
                valueCode: "A"
              - url: "${fhirServerUrl}/fhir/StructureDefinition/Esmd-Ext-ServiceCode"
                valueCode: "EEP"
              - url: "${fhirServerUrl}/fhir/StructureDefinition/Esmd-Ext-ServiceStartDate"
                valueDate: "2025-05-01"
              - url: "${fhirServerUrl}/fhir/StructureDefinition/Esmd-Ext-ServiceEndDate"
                valueDate: "2025-12-31"
          request:
            method: "PUT"
            url: "Practitioner/P${PractitionerIdValue}"
        - fullUrl: "urn:uuid:1"
          resource:
            resourceType: "Practitioner"
            id: "P${PractitionerIdValue}"
            meta:
              profile:
                - "${fhirServerUrl}/fhir/StructureDefinition/Esmd-Practitioner"
              security:
                - system: "http://terminology.hl7.org/CodeSystem/v3-Confidentiality"
                  code: "V"
                  display: "very restricted"
            telecom:
              - system: "phone"
                value: "555-123-4568"
                use: "work"
            name:
              - family: "Bone2"
                given:
                  - "Ronald2"
                prefix:
                  - "Dr"
            address:
              - use: "work"
                line:
                  - "1004 HEALTHCARE DR"
                city: "AMHERST"
                state: "MA"
                postalCode: "01002"
            gender: "male"
            active: true
            extension:
              - url: "${fhirServerUrl}/fhir/StructureDefinition/Esmd-Ext-NPI"
                valueString: "1457396376"
              - url: "${fhirServerUrl}/fhir/StructureDefinition/Esmd-Ext-ProviderTaxId"
                valueString: "HIH1234"
              - url: "${fhirServerUrl}/fhir/StructureDefinition/Esmd-Ext-ActionRequestedCode"
                valueCode: "A"
              - url: "${fhirServerUrl}/fhir/StructureDefinition/Esmd-Ext-ServiceCode"
                valueCode: "EEP"
              - url: "${fhirServerUrl}/fhir/StructureDefinition/Esmd-Ext-ServiceStartDate"
                valueDate: "2025-10-01"
              - url: "${fhirServerUrl}/fhir/StructureDefinition/Esmd-Ext-ServiceEndDate"
                valueDate: "2025-12-31"
          request:
            method: "PUT"
            url: "Practitioner/P${PractitionerIdValue}"

